AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  dormakaba-2025-task\

  Sample SAM Template for dormakaba-2025-task\

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  CertificateProcessorFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: certificate-processor-function-sam
      PackageType: Zip
      Architectures:
        - x86_64
      Handler: app.handler
      Runtime: nodejs22.x
      Timeout: 30
      Environment:
        Variables:
          DYNAMO_TABLE:
            Ref: PubkeyTable
          NODE_OPTIONS: --enable-source-maps
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 's3:GetObject'
              Resource: 'arn:aws:s3:::*'
            - Effect: Allow
              Action:
                - 'dynamodb:PutItem'
              Resource:
                'Fn::Join':
                  - ''
                  - - 'arn:aws:dynamodb:'
                    - Ref: 'AWS::Region'
                    - ':'
                    - Ref: 'AWS::AccountId'
                    - ':table/'
                    - Ref: PubkeyTable
      Events:
        CertificateUploaded:
          Type: S3
          Properties:
            Bucket:
              Ref: CertificatesBucket
            Events:
              - 's3:ObjectCreated:*'
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Format: esm
        Minify: false
        Target: 'es2020'
        Sourcemap: true
        EntryPoints:
          - app.ts

  CertificatesBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: certificates-bucket-sam

  PubkeyTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: pubkey-table-sam
      PrimaryKey:
        Type: S
        Name: common-name
